project_id = "qszmmysnwjvywpsofbgs"

[functions.fb-capi]
verify_jwt = false

[functions.google-capi]
verify_jwt = false

[functions.ga4-proxy]
verify_jwt = false

[functions.onboarding-chat]
verify_jwt = false

[functions.messenger-webhook]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
