#!/bin/bash

# DigiWebDex Deployment Script
# Automatically creates isolated project directory and deploys services
# Safe for multi-site VPS - does not modify existing directories

set -e

# Configuration
PROJECT_NAME="digiwebdex"
PROJECT_DIR="/var/www/${PROJECT_NAME}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================"
echo "DigiWebDex VPS Deployment Script"
echo -e "========================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${YELLOW}Warning: Not running as root. Some operations may fail.${NC}"
fi

# Safety check - list existing directories
echo "Existing directories in /var/www/:"
ls -la /var/www/ 2>/dev/null || echo "  (none or access denied)"
echo ""

# Confirm deployment
echo -e "${YELLOW}This script will create: ${PROJECT_DIR}${NC}"
echo "It will NOT modify any existing directories."
read -p "Continue? (y/N): " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled."
    exit 0
fi

# Step 1: Create project directory structure
echo ""
echo "Step 1: Creating isolated project directory..."
mkdir -p ${PROJECT_DIR}/{backend,frontend/dist,database,nginx/ssl,scripts,logs/backend,logs/nginx,backups}
echo -e "${GREEN}✓ Directory structure created${NC}"

# Step 2: Copy files
echo ""
echo "Step 2: Copying project files..."
if [ -d "${SCRIPT_DIR}/../backend" ]; then
    cp -r ${SCRIPT_DIR}/../backend/* ${PROJECT_DIR}/backend/
    echo "  ✓ Backend files copied"
fi

if [ -d "${SCRIPT_DIR}/../database" ]; then
    cp -r ${SCRIPT_DIR}/../database/* ${PROJECT_DIR}/database/
    echo "  ✓ Database files copied"
fi

if [ -d "${SCRIPT_DIR}/../nginx" ]; then
    cp -r ${SCRIPT_DIR}/../nginx/* ${PROJECT_DIR}/nginx/
    echo "  ✓ Nginx config copied"
fi

if [ -f "${SCRIPT_DIR}/../docker-compose.yml" ]; then
    cp ${SCRIPT_DIR}/../docker-compose.yml ${PROJECT_DIR}/
    echo "  ✓ Docker Compose file copied"
fi

cp ${SCRIPT_DIR}/*.sh ${PROJECT_DIR}/scripts/ 2>/dev/null || true
echo -e "${GREEN}✓ Files copied${NC}"

# Step 3: Create environment file if not exists
echo ""
echo "Step 3: Setting up environment..."
if [ ! -f "${PROJECT_DIR}/.env" ]; then
    cat > ${PROJECT_DIR}/.env << 'ENVEOF'
# DigiWebDex Environment Configuration
# Generated by deploy.sh

# Project
PROJECT_NAME=digiwebdex
PROJECT_DIR=/var/www/digiwebdex

# Database (isolated - unique port)
DB_NAME=digiwebdex_db
DB_USER=digiwebdex_user
DB_PASSWORD=CHANGE_ME_TO_SECURE_PASSWORD
DB_PORT=5433

# Backend (isolated port)
BACKEND_PORT=3001
NODE_ENV=production

# Authentication
JWT_SECRET=CHANGE_ME_TO_RANDOM_32_CHAR_STRING
JWT_EXPIRES_IN=7d

# Email
RESEND_API_KEY=
ADMIN_EMAIL=digiwebdex@gmail.com

# URLs
FRONTEND_URL=https://digiwebdex.com
API_URL=https://digiwebdex.com/api
ENVEOF
    echo -e "${YELLOW}⚠ Created .env file - EDIT IT WITH YOUR VALUES!${NC}"
    echo "  nano ${PROJECT_DIR}/.env"
else
    echo "  .env already exists, skipping"
fi

# Step 4: Set permissions
echo ""
echo "Step 4: Setting permissions..."
chown -R www-data:www-data ${PROJECT_DIR}/frontend ${PROJECT_DIR}/logs 2>/dev/null || true
chmod -R 755 ${PROJECT_DIR}
chmod 600 ${PROJECT_DIR}/.env
echo -e "${GREEN}✓ Permissions set${NC}"

# Step 5: Verify Docker
echo ""
echo "Step 5: Checking Docker..."
if command -v docker &> /dev/null; then
    echo -e "${GREEN}✓ Docker installed${NC}"
    docker --version
else
    echo -e "${RED}✗ Docker not found. Install with: curl -fsSL https://get.docker.com | sh${NC}"
    exit 1
fi

if command -v docker compose &> /dev/null; then
    echo -e "${GREEN}✓ Docker Compose installed${NC}"
else
    echo -e "${RED}✗ Docker Compose not found${NC}"
    exit 1
fi

# Step 6: Check port availability
echo ""
echo "Step 6: Checking port availability..."
check_port() {
    if netstat -tlnp 2>/dev/null | grep -q ":$1 "; then
        echo -e "${RED}✗ Port $1 is in use!${NC}"
        return 1
    else
        echo -e "${GREEN}✓ Port $1 is available${NC}"
        return 0
    fi
}

check_port 3001 || echo "  Consider changing BACKEND_PORT in .env"
check_port 5433 || echo "  Consider changing DB_PORT in .env"

# Summary
echo ""
echo -e "${GREEN}========================================"
echo "Deployment Preparation Complete!"
echo -e "========================================${NC}"
echo ""
echo "Project directory: ${PROJECT_DIR}"
echo ""
echo "Next steps:"
echo "  1. Edit environment file:"
echo "     nano ${PROJECT_DIR}/.env"
echo ""
echo "  2. Upload frontend build:"
echo "     scp -r ./dist/* root@vps:${PROJECT_DIR}/frontend/dist/"
echo ""
echo "  3. Start services:"
echo "     cd ${PROJECT_DIR}"
echo "     docker compose up -d"
echo ""
echo "  4. Configure Nginx (see README_DEPLOYMENT.md)"
echo ""
echo "  5. Setup SSL certificate:"
echo "     certbot certonly --standalone -d digiwebdex.com"
